# Generated by Django 4.1 on 2024-04-02 14:40

import IEC.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aerogenerador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("potencia_nominal", models.FloatField()),
                ("diametro_rotor", models.FloatField()),
                ("altura_buje", models.FloatField()),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ag_conf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("ws_avg", IEC.models.NonStrippingCharField(max_length=200)),
                (
                    "ws_min",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "ws_max",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "ws_std",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                ("wd_avg", IEC.models.NonStrippingCharField(max_length=200)),
                (
                    "wd_min",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "wd_max",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "wd_std",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                ("pins_avg", IEC.models.NonStrippingCharField(max_length=200)),
                (
                    "pins_min",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "pins_max",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "pins_std",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                ("p_teo_avg", IEC.models.NonStrippingCharField(max_length=200)),
                (
                    "p_teo_min",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "p_teo_max",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "p_teo_std",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                ("date", IEC.models.NonStrippingCharField(blank=True, max_length=200)),
                (
                    "no_serie",
                    IEC.models.NonStrippingCharField(blank=True, max_length=200),
                ),
                (
                    "aerogenerador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
            bases=(models.Model, IEC.models.NonStrippingCharField),
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrumento", models.CharField(max_length=200)),
                ("variable", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="parque_eolico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fabricante", models.CharField(max_length=200)),
                (
                    "especificaciones",
                    models.FileField(blank=True, upload_to="especificaciones"),
                ),
                (
                    "instrumentoID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.instrumento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud", models.FloatField(blank=True)),
                ("longitud", models.FloatField(blank=True)),
                ("altura", models.FloatField(blank=True)),
                ("direccion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TorreMet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion Torre"),
                ),
                ("SensoresID", models.ManyToManyField(to="IEC.sensor")),
                (
                    "ubicacionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IEC.ubicacion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorMed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("mean", models.FloatField()),
                ("max", models.FloatField(blank=True)),
                ("min", models.FloatField(blank=True)),
                ("std", models.FloatField(blank=True)),
                ("unidad", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                (
                    "sensorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="IEC.sensor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="parque_conf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("aerogeneradores", models.ManyToManyField(to="IEC.ag_conf")),
            ],
        ),
        migrations.CreateModel(
            name="DescripcionMedi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scatter_power", models.FileField(blank=True, upload_to="AG_POWER")),
                ("scatter_wind", models.FileField(blank=True, upload_to="AG_WIND")),
                (
                    "scatter_turbulence",
                    models.FileField(blank=True, upload_to="AG_TUR"),
                ),
                ("special_data", models.FileField(blank=True, upload_to="AG_SPECIAL")),
                ("scatter_rot_PA", models.FileField(blank=True, upload_to="AG_PITCH")),
                (
                    "status_signals",
                    models.FileField(blank=True, upload_to="AG_SIGNALS"),
                ),
                ("scatter_air_den", models.FileField(blank=True, upload_to="AG_AIR")),
                (
                    "scatter_wind_shear",
                    models.FileField(blank=True, upload_to="AG_SHEAR"),
                ),
                (
                    "scatter_wind_shear_TC",
                    models.FileField(blank=True, upload_to="AG_SHEAR_TC"),
                ),
                ("wind_shear_correction", models.FloatField(blank=True)),
                ("avg_air_density", models.FloatField(blank=True)),
                (
                    "aerogeneradorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="descripcion_sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fotografias", models.FileField(blank=True, upload_to="AG_SITIO")),
                ("mapa", models.FileField(blank=True, upload_to="AG_MAPA")),
                ("limites", models.FileField(blank=True, upload_to="AG_LIMITES")),
                (
                    "calibracion",
                    models.FileField(blank=True, upload_to="AG_CALIBRACION"),
                ),
                ("ubicacion", models.FileField(blank=True, upload_to="AG_UBICACION")),
                (
                    "aerogeneradorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="descripcion_equipamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esquema_met", models.FileField(blank=True, upload_to="AG_MET")),
                ("documentacion", models.FileField(blank=True, upload_to="AG_DOC")),
                (
                    "aerogeneradorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AG_identificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fabricante", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=200)),
                ("numeroSerie", models.CharField(max_length=200)),
                ("anoProduccion", models.DateTimeField(blank=True)),
                (
                    "aerogeneradorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="aerogenerador_st",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(blank=True)),
                ("viento_avg", models.FloatField(blank=True)),
                ("viento_max", models.FloatField(blank=True)),
                ("viento_min", models.FloatField(blank=True)),
                ("viento_std", models.FloatField(blank=True)),
                ("p_avg", models.FloatField(blank=True)),
                ("p_max", models.FloatField(blank=True)),
                ("p_min", models.FloatField(blank=True)),
                ("p_std", models.FloatField(blank=True)),
                ("posicion", models.FloatField(blank=True)),
                ("posicion_min", models.FloatField(blank=True)),
                ("posicion_max", models.FloatField(blank=True)),
                ("posicion_std", models.FloatField(blank=True)),
                ("pteo_avg", models.FloatField(blank=True)),
                ("pteo_min", models.FloatField(blank=True)),
                ("pteo_max", models.FloatField(blank=True)),
                ("pteo_std", models.FloatField(blank=True)),
                (
                    "ag_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="IEC.aerogenerador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aerogenerador",
            name="parque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="IEC.parque_eolico"
            ),
        ),
    ]
