# Generated by Django 4.1 on 2024-04-03 19:25

import IEC.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("IEC", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ag_conf",
            name="label_col",
            field=IEC.models.NonStrippingCharField(blank=True, max_length=200),
        ),
    ]
